# Generated by Django 3.2.7 on 2021-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fname',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
