# Generated by Django 3.2.7 on 2021-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210929_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.FileField(blank=True, default='avtar.jpg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
