# Generated by Django 3.2.7 on 2021-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.FileField(blank=True, default='avtar.png', null=True, upload_to='profile'),
        ),
    ]
