# Generated by Django 3.2.7 on 2021-10-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
