# Generated by Django 3.2.7 on 2021-10-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename_test_name_appointment_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Sample to be collected', max_length=20),
        ),
    ]
