# Generated by Django 3.2.7 on 2021-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=10, unique=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='emp-pic')),
            ],
        ),
    ]
