# Generated by Django 3.2.7 on 2021-10-11 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=10)),
                ('test_added_by', models.DateTimeField(default=datetime.datetime(2021, 10, 11, 11, 23, 7, 28184))),
                ('test_desc', models.TextField()),
                ('test_rate', models.IntegerField()),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
