# Generated by Django 3.2.7 on 2021-10-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
